from routes.frontend.main import *
from routes.frontend.auth import *
from routes.admin.category import *
from routes.admin.dashboard import *
from routes.admin.product import *
from routes.admin.auth import *
from routes.admin.customer import *
from routes.admin.user import *
from routes.admin.order_management import *